preload = ~/Pictures/Wallpapers/b-030.jpg

wallpaper {
  monitor = DP-1
  path = ~/Pictures/Wallpapers/b-030.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/Pictures/Wallpapers/b-030.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = ~/Pictures/Wallpapers/b-030.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Wallpapers/b-030.jpg
  fit_mode = cover
}

splash = false
